# NumPy arrays

In [1]:
# numpy makes use of low-level libraries for working with vector and matrices such as
# Linear Algebra Subprograms (BLAS) and the Linear Algebra Package (LAPACK)
import numpy as np

# int array
ary = np.array([1, 2, 3, 4])
print(ary)
print(ary.dtype)

[1 2 3 4]
int64


In [2]:
# float array
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [3]:
# change array type
arr = np.array([2, 3, 5, 7])
print(arr)
print(arr.dtype)
arr = arr.astype(np.float64)
print(arr)
print(arr.dtype)

[2 3 5 7]
int64
[2. 3. 5. 7.]
float64


In [4]:
# element access: arr[i]
ary = np.array([0, 2, 4, 6])
print(ary[0])
print(ary[1])

0
2


In [5]:
# slicing too: arr[start:stop:step]
futatsu = ary[:2]
print(futatsu)
suri_x = ary[1::2]
print(suri_x)

[0 2]
[2 6]


In [6]:
# array arithmetics (component-wise)
arr_0 = np.array([2, 5, 7, 3])
arr_1 = np.array([5, 3, -9, 8])
print('2 * arr_1 =', 2 * arr_1)
print('arr_0 + arr_1  =', arr_0 + arr_1)
print('arr_0 - arr_1  =', arr_0 - arr_1)
print('arr_0 * arr_1  =', arr_0 * arr_1)
print('arr_0 / arr_1  =', arr_0 / arr_1)
print('arr_1 ** arr_0 =', arr_1 ** arr_0)

2 * arr_1 = [ 10   6 -18  16]
arr_0 + arr_1  = [ 7  8 -2 11]
arr_0 - arr_1  = [-3  2 16 -5]
arr_0 * arr_1  = [ 10  15 -63  24]
arr_0 / arr_1  = [ 0.4         1.66666667 -0.77777778  0.375     ]
arr_1 ** arr_0 = [      25      243 -4782969      512]


In [7]:
# create array of numbers at regular intervals
np.linspace(0, 1, 5)  # (start, inclusive_end, n_elem)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.arange(0, 1.3, 0.3)  # (start, end, step)

array([0. , 0.3, 0.6, 0.9, 1.2])

In [11]:
# higher dimensional arrays
mat = np.array([[3, 4], [7, 6]])
vec = np.array([1, 2])
print(mat.shape)  # the number of element in the shape tuple in the number of dimensions
print(vec.shape)  # the values of the elements are the number of elements inside each dimension (each nested array)

(2, 2)
(2,)


In [12]:
# reshape to flat array
mat.reshape(4,)

array([3, 4, 7, 6])

In [13]:
# dimensions can also be checked this way:
mat.ndim

2

In [14]:
# higher dimensional arrays
mat1 = [[1, 2], [3, 4]]
mat2 = [[5, 6], [7, 8]]
mat3 = [[9, 10], [11, 12]]
arr_3d = np.array([mat1, mat2, mat3])
print(f'arr_3d =\n{arr_3d}')
print('arr_3d.shape:', arr_3d.shape)

arr_3d =
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
arr_3d.shape: (3, 2, 2)


In [14]:
# access an element in a multi-dimensional array
print(mat)
mat[1, 0]

[[3 4]
 [7 6]]


7

In [15]:
# also supports slicing
mat[:, 0]  # all members of a single column (0th column)

array([3, 7])

# Matrices

In [15]:
# identity matrix
np.eye(3)  # np.identity(3) also works

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# transpose of a matrix
mat = np.array([[1, 2], [3, 4]])
print(mat)
print("transposed:")
print(mat.transpose())
print(mat.T)  # object property that returns the transpose

[[1 2]
 [3 4]]
transposed:
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [23]:
# trace of a matrix: the sum of the elements along the leading diagonal
mat.trace()

5


In [24]:
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 1], [0, 1]])
A @ B  # matrix multiplication operator= @ 

array([[-1,  3],
       [-3,  7]])

In [25]:
# keep in mind this is different from component-wise multiplication:
A * B

array([[-1,  2],
       [ 0,  4]])

In [26]:
# the Identity Matrix is a neutral element under matrix multiplication
A = np.array([[2, 3], [5, 7]])
I = np.eye(2, dtype=np.int64)  # identity matrix of ints (otherwise it would be floats)
A @ I

array([[2, 3],
       [5, 7]])

In [27]:
# Determinants and Inverses

# Determinant: a scalar value that is a function of the entries of a square matrix
# It allows characterizing some properties of the matrix and the linear map represented by the matrix
np.linalg.det(A)

-0.9999999999999987

In [33]:
# Inverse
# AB = BA = I; where I is the identity matrix and B is the inverse of A
# a matrix is not singular (that is, has an inverse) if, and only if, the determinant of that matrix is not 0
print(A)
Ainv=np.linalg.inv(A)
print(Ainv)

# verify is indeed the matrix inverse of A
print(f'A @ Ainv =\n{A @ Ainv}')
print(f'Ainv @ A =\n{Ainv @ A}')

[[2 3]
 [5 7]]
[[-7.  3.]
 [ 5. -2.]]
A @ Ainv =
[[ 1.00000000e+00 -4.44089210e-16]
 [-7.10542736e-15  1.00000000e+00]]
Ainv @ A =
[[ 1.00000000e+00 -8.88178420e-16]
 [-1.33226763e-15  1.00000000e+00]]


In [36]:
# other functions
import scipy as sp  # use scipy.linalg to compute the equilavent matrix operations such expm, sinm, tanm, etc...

sp.linalg.expm(A)  # matrix exponential

array([[2070.11707525, 2942.33805282],
       [4903.8967547 , 6974.01382995]])

In [37]:
sp.linalg.sinm(A)  # matrix sine

array([[-0.01358369,  0.13646243],
       [ 0.22743739,  0.2138537 ]])

In [38]:
# Systems of linear equations
# Ax = b; where A is the matrix containing the coefficients from the equation,
#         x is the unknown (column) vector and b is the vector with the known values

# example:
# 3x_1 - 2x_2 +x_3 = 7
# x_1 + x_2 - 2x_3 = -4
# -3x_1 - 2x_2 + x_3 = 1
A = np.array([[3, -2, 1],
              [1, 1, -2],
              [-3, -2, 1]])
b = np.array([7, -4, 1])
np.linalg.solve(A, b)

array([ 1., -1.,  2.])

In [39]:
# Ax = b; x = A^-1(b) 
np.linalg.inv(A) @ b  # this also gives us the solution to the equation (but is slower and more error-prone)

array([ 1., -1.,  2.])

In [41]:
# Eigenvalues and Eigenvectors
# Ax = λx; where A is a square (n x n) matrix, x is a vector, and λ is a number
#          Numbers λ for which there is an x that solves this equation are called eigenvalues,
#          and the corresponding vectors x are called eigenvectors.

A = np.array([[3, -1, 4],
              [-1, 0, -1],
              [4, -1, 2]])
v, B = np.linalg.eig(A)  # v is a 1-d array containing the eigenvalues
print(v)            # and B is a 2-d array where each column correspond to an eigenvector
print(B)

[ 6.82315616 -1.53711415 -0.28604201]
[[ 0.73271846 -0.65131465  0.19726352]
 [-0.20260301  0.06794858  0.97690072]
 [ 0.64967352  0.75575937  0.08217113]]


In [43]:
i = 0 # first eigenvalue/eigenvector pair
lambda0 = v[i]
print(lambda0)

x0 = B[:, i]  # ith column of B (first eigenvector)
print(x0)

6.823156164525971
[ 0.73271846 -0.20260301  0.64967352]


In [44]:
# eigenvectors are normalized (norm=1)
np.linalg.norm(x0)

1.0

In [45]:
# sparse matrices
A = np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]])
sp_A = sp.sparse.csr_matrix(A)
print(sp_A)  # compressed sparse row (csr) matrix representation
print(sp_A.toarray())

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
# diagonal patterns
T = sp.sparse.diags([-1, 2, -1], (-1, 0, 1), shape=(5, 5), format='csr')
print(T)
print(T.toarray())
print('T.shape:', T.shape)
print('T.ndim:', T.ndim)
print('T.format:', T.format)

  (0, 0)	2.0
  (0, 1)	-1.0
  (1, 0)	-1.0
  (1, 1)	2.0
  (1, 2)	-1.0
  (2, 1)	-1.0
  (2, 2)	2.0
  (2, 3)	-1.0
  (3, 2)	-1.0
  (3, 3)	2.0
  (3, 4)	-1.0
  (4, 3)	-1.0
  (4, 4)	2.0
[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]
T.shape: (5, 5)
T.ndim: 2
T.format: csr


In [47]:
# sparse solving routines
sp.sparse.linalg.spsolve(T, np.array([0, 1, 1, 2, 3]))

array([2.33333333, 4.66666667, 6.        , 6.33333333, 4.66666667])